=== 2001asjad/aqa-test-tools/PerfNext/machines/master_machine_list.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="machinelist" type="MachineListType"/>

<!-- The root element of a machine list document. -->
<xs:complexType name="MachineListType">
	<xs:sequence>
		<xs:element name="defaults" type="DefaultsType" minOccurs="0"/>
		<xs:element name="template" type="TemplateType"/>
		<xs:element name="machines" type="MachinesType"/>
		<xs:element name="hosts" type="HostsType"/>
	</xs:sequence>
</xs:complexType>

<!-- The list of machine entries -->
<xs:complexType name="MachinesType">
	<xs:sequence>
		<xs:element name="machine" type="MachineType" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<!-- The list of host entries -->
<xs:complexType name="HostsType">
	<xs:sequence>
		<xs:element name="host" type="HostType" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<!-- A container for the machine and host templates -->
<xs:complexType name="TemplateType">
	<xs:sequence>
		<xs:element name="machine" type="MachineType"/>
		<xs:element name="host" type="HostType"/>
	</xs:sequence>
</xs:complexType>

<!-- Defaults countainer - allows known values for various parameters be
     specified so they can be offered as options by editing tools. Typically
     these parameters are ones that have functional meaning (for example, in
     establishing the exact build type that is applicable to a machine). -->
<xs:complexType name="DefaultsType">
	<xs:all>
		<xs:element name="ostypes">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="os" type="TypedString" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="cputypes">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="cputype" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="threadingtypes">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="threading" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="bitcounts">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="bits" type="xs:integer" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="netspeeds">
			<xs:complexType>
				<xs:all>
					<xs:element name="interface">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="speed" type="WithUnits" minOccurs="0" maxOccurs="unbounded"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:all>
			</xs:complexType>
		</xs:element>
		<xs:element name="addresstypes">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="address" type="TypedString" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="cpuspeeds">
			<xs:complexType>
				<xs:all>
					<xs:element name="cpus">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="speed" type="WithUnits" minOccurs="0" maxOccurs="unbounded"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:all>
			</xs:complexType>
		</xs:element>
		<xs:element name="memoryspeeds">
			<xs:complexType>
				<xs:all>
					<xs:element name="memory">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="speed" type="WithUnits" minOccurs="0" maxOccurs="unbounded"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:all>
			</xs:complexType>
		</xs:element>
		<xs:element name="memorysizes">
			<xs:complexType>
				<xs:all>
					<xs:element name="memory">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="capacity" type="WithUnits" minOccurs="0" maxOccurs="unbounded"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:all>
			</xs:complexType>
		</xs:element>
	</xs:all>
</xs:complexType>

<!-- A machine definition -->
<xs:complexType name="MachineType">
	<xs:all>
		<xs:element name="name" type="xs:string"/>
		<xs:element name="serial" type="xs:string"/>
		<xs:element name="manufacturer" type="xs:string"/>
		<xs:element name="model" type="xs:string"/>
		<xs:element name="description" type="xs:string"/>
		<xs:element name="location" type="LocationType"/>
		<xs:element name="owners" type="OwnersType"/>
		<xs:element name="architecture" type="ArchitectureType"/>
		<xs:element name="hardware" type="HardwareType"/>
	</xs:all>
	<xs:attribute name="id" type="xs:integer"/>
</xs:complexType>

<!-- A host definition -->
<xs:complexType name="HostType">
	<xs:all>
		<xs:element name="name" type="xs:string"/>
		<xs:element name="domain" type="xs:string"/>
		<xs:element name="machine" type="HostMachineType"/>
		<xs:element name="os" type="TypedString"/>
		<xs:element name="description" type="xs:string"/>
		<xs:element name="addresses" type="AddressesType"/>
		<xs:element name="axxon" type="AxxonType"/>
		<xs:element name="jobgenerator" type="JobGeneratorType"/>
		<xs:element name="STAF" type="STAFConfigType"/>
	</xs:all>
	<xs:attribute name="id" type="xs:integer"/>
</xs:complexType>

<!-- A reference within a host definition to a machine's id number -->
<xs:complexType name="HostMachineType">
	<xs:sequence/>
	<xs:attribute name="id" type="xs:integer"/>
</xs:complexType>

<!-- A machine's architecture definition -->
<xs:complexType name="ArchitectureType">
	<xs:sequence>
		<xs:element name="cpuvendor" type="xs:string"/>
		<xs:element name="cpuname" type="xs:string"/>
		<xs:element name="cputype" type="xs:string"/>
		<xs:element name="bits" type="xs:integer"/>
		<xs:element name="compatible" type="CompatibleArchitectureType" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<!-- A compatible architecture definition -->
<xs:complexType name="CompatibleArchitectureType">
	<xs:all>
		<xs:element name="cputype" type="xs:string"/>
		<xs:element name="bits" type="xs:integer"/>
	</xs:all>
	<xs:attribute name="id" type="xs:integer"/>
</xs:complexType>

<!-- A machine's hardware definition -->
<xs:complexType name="HardwareType">
	<xs:all>
		<xs:element name="cpus" type="CPUsType"/>
		<xs:element name="fsbspeed" type="IntWithUnits"/>
		<xs:element name="caches" type="CachesType"/>
		<xs:element name="memory" type="MemoryType"/>
		<xs:element name="network" type="NetworkType"/>
	</xs:all>
</xs:complexType>

<xs:complexType name="CPUsType">
	<xs:all>
		<xs:element name="physical" type="xs:integer"/>
		<xs:element name="logical" type="xs:integer"/>
		<xs:element name="threading" type="xs:string"/>
		<xs:element name="speed" type="FloatWithUnits"/>
	</xs:all>
</xs:complexType>

<xs:complexType name="CachesType">
	<xs:sequence>
		<xs:element name="cache" minOccurs="0" maxOccurs="unbounded">
			<xs:complexType>
				<xs:simpleContent>
					<xs:extension base="xs:integer">
						<xs:attribute name="id" type="xs:integer"/>
						<xs:attribute name="type" type="xs:string"/>
						<xs:attribute name="units" type="xs:string"/>
					</xs:extension>
				</xs:simpleContent>
			</xs:complexType>
		</xs:element>
		<xs:element name="notes" type="xs:string"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="OwnersType">
	<xs:sequence>
		<xs:element name="owner" type="TypedIdString" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="MemoryType">
	<xs:all>
		<xs:element name="speed" type="FloatWithUnits"/>
		<xs:element name="capacity" type="IntWithUnits"/>
	</xs:all>
	<xs:attribute name="type" type="xs:string"/>
</xs:complexType>

<xs:complexType name="NetworkType">
	<xs:sequence>
		<xs:element name="interface" type="InterfaceType" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="InterfaceType">
	<xs:all>
		<xs:element name="port" type="xs:string"/>
		<xs:element name="speed" type="IntWithUnits"/>
	</xs:all>
	<xs:attribute name="id" type="xs:integer"/>
	<xs:attribute name="type" type="xs:string"/>
</xs:complexType>

<!-- A host's addresses definition. Each address has an 'interface' attribute
     which refers to the 'id' attribute of a physical network interface on
     the associated machine. -->
<xs:complexType name="AddressesType">
	<xs:sequence>
		<xs:element name="address" minOccurs="0" maxOccurs="unbounded">
			<xs:complexType>
				<xs:simpleContent>
					<xs:extension base="xs:string">
						<xs:attribute name="id" type="xs:integer"/>
						<xs:attribute name="hostname" type="xs:string"/>
						<xs:attribute name="type" type="xs:string"/>
						<xs:attribute name="interface" type="xs:integer"/>
					</xs:extension>
				</xs:simpleContent>
			</xs:complexType>
		</xs:element>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="LocationType">
	<xs:all>
		<xs:element name="room" type="xs:string"/>
		<xs:element name="site" type="xs:string"/>
		<xs:element name="country" type="xs:string"/>
	</xs:all>
</xs:complexType>

<!-- An element with a name attribute, containing string data -->
<xs:complexType name="NamedString">
	<xs:simpleContent>
		<xs:extension base="xs:string">
			<xs:attribute name="name" type="xs:string"/>
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>

<!-- An element with an id attribute, containing string data -->
<xs:complexType name="IdString">
	<xs:simpleContent>
		<xs:extension base="xs:string">
			<xs:attribute name="id" type="xs:integer"/>
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>

<!-- An element with id and name attributes, containing string data -->
<xs:complexType name="NamedIdString">
	<xs:simpleContent>
		<xs:extension base="xs:string">
			<xs:attribute name="id" type="xs:integer"/>
			<xs:attribute name="name" type="xs:string"/>
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>

<!-- An element with a type attribute, containing string data -->
<xs:complexType name="TypedString">
	<xs:simpleContent>
		<xs:extension base="xs:string">
			<xs:attribute name="type" type="xs:string"/>
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>

<!-- An element with id and type attributes, containing string data -->
<xs:complexType name="TypedIdString">
	<xs:simpleContent>
		<xs:extension base="xs:string">
			<xs:attribute name="id" type="xs:integer"/>
			<xs:attribute name="type" type="xs:string"/>
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>

<!-- An element with a units attribute, containing integer data -->
<xs:complexType name="IntWithUnits">
	<xs:simpleContent>
		<xs:extension base="xs:integer">
			<xs:attribute name="units" type="xs:string"/>
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>

<!-- An element with a units attribute, containing floating point data -->
<xs:complexType name="FloatWithUnits">
	<xs:simpleContent>
		<xs:extension base="xs:float">
			<xs:attribute name="units" type="xs:string"/>
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>

<!-- An element with a units attribute -->
<xs:complexType name="WithUnits">
	<xs:simpleContent>
		<xs:extension base="xs:string">
			<xs:attribute name="units" type="xs:string"/>
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>

<xs:complexType name="AxxonType">
	<xs:sequence>
		<xs:element name="capabilities" type="AxxonCapabilitiesType"/>
		<xs:element name="param" type="NamedIdString" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

<xs:complexType name="AxxonCapabilitiesType">
	<xs:sequence>
		<xs:element name="capability" type="IdString" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="STAFConfigType">
	<xs:all>
		<xs:element name="entries" type="STAFEntryType"/>
		<xs:element name="vars" type="STAFVarType"/>
	</xs:all>
	<xs:attribute name="trust" type="xs:boolean"/>
</xs:complexType>

<xs:complexType name="STAFVarType">
	<xs:sequence>
		<xs:element name="var" type="NamedIdString" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="STAFEntryType">
	<xs:sequence>
		<xs:element name="entry" type="IdString" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="JobGeneratorType">
	<xs:all>
		<xs:element name="staxcontroller" type="xs:string"/>
		<xs:element name="capabilities" type="JGCapabilitiesType"/>
		<xs:element name="restrictions" type="JGRestrictionsType"/>
	</xs:all>
	<xs:attribute name="enabled" type="xs:boolean"/>
</xs:complexType>

<xs:complexType name="JGCapabilitiesType">
	<xs:sequence>
		<xs:element name="capability" type="JGCapabilityType" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="JGRestrictionsType">
	<xs:sequence>
		<xs:element name="restriction" type="NamedIdString" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="JGCapabilityType">
	<xs:sequence>
		<xs:element name="property" type="NamedIdString" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="id" type="xs:integer"/>
	<xs:attribute name="name" type="xs:string"/>
	<xs:attribute name="bits" type="xs:string"/>
</xs:complexType>

</xs:schema>

=== 2001asjad/aqa-test-tools/PerfNext/machines/template_master_machine_list.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
-->
<!--
 | Master machine list. Includes:
 | - Non-functional information for team members 
 | - Functional stuff for Axxon (via a transform)
 | - Functional stuff for job submission tool (via a transform)
 |
 | Machine and host elements in this list are created and modified
 | automatically by editing tools, or can be created by hand. In the
 | latter case, ensure your changes validate successfully with the
 | corresponding stylesheet (master_machine_list.xsd).
 -->


<machinelist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="master_machine_list.xsd">
    <defaults><!-- Add values to this section to make them appear as selections in the editor. -->
        <ostypes>
            <os type="Linux"/>
            <os type="Windows"/>
            <os type="AIX"/>
            <os type="MVS"/>
            <os type="HP-UX"/>
            <os type="Solaris"/>
            <os type="Darwin"/>
        </ostypes>
        <bitcounts>
            <bits>32</bits>
            <bits>64</bits>
            <bits>31</bits>
        </bitcounts>
        <axxonlogintypes>
            <shell>STAF</shell>
            <shell>SSH</shell>
        </axxonlogintypes>
        <axxonloginids>
            <username>jbench</username>
            <username>bench</username>
        </axxonloginids>
        <cputypes>
            <cputype>x86</cputype>
            <cputype>AMD64</cputype>
            <cputype>PPC</cputype>
            <cputype>PPCLE</cputype>
            <cputype>z Series</cputype>
            <cputype>PA-RISC</cputype>
            <cputype>Itanium</cputype>
            <cputype>SPARC</cputype>
        </cputypes>
        <threadingtypes>
            <threading>none</threading>
            <threading>SMT</threading>
            <threading>HT</threading>
        </threadingtypes>
        <netspeeds>
            <interface>
                <speed units="Mbit"/>
                <speed units="Gbit"/>
            </interface>
        </netspeeds>
        <addresstypes>
            <address type="IPv4"/>
            <address type="IPv6"/>
        </addresstypes>
        <cpuspeeds>
            <cpus>
                <speed units="MHz"/>
                <speed units="GHz"/>
            </cpus>
        </cpuspeeds>
        <memoryspeeds>
            <memory>
                <speed units="MHz"/>
                <speed units="GHz"/>
            </memory>
        </memoryspeeds>
        <memorysizes>
            <memory>
                <capacity units="MB"/>
                <capacity units="GB"/>
            </memory>
        </memorysizes>
    </defaults>
    <template><!-- Templates for machine and host entries. -->
        <machine id="0">
            <name/>
            <serial/>
            <manufacturer/>
            <model/>
            <description/>
            <location>
                <room/>
                <site/>
                <country/>
            </location>
            <owners>
                <owner id="1" type="eAMT"/>
            </owners>
            <architecture>
                <cpuvendor/>
                <cpuname/>
                <cputype>x86</cputype>
                <bits>32</bits>
            </architecture>
            <hardware>
                <cpus>
                    <physical>1</physical>
                    <logical>1</logical>
                    <threading>none</threading>
                    <speed units="MHz">1</speed>
                </cpus>
                <fsbspeed units="MHz">1</fsbspeed>
                <caches>
                    <cache id="1" type="L1" units="KB">0</cache>
                    <notes/>
                </caches>
                <memory type="DDR">
                    <speed units="MHz">1</speed>
                    <capacity units="MB">1</capacity>
                </memory>
                <network>
                    <interface type="Ethernet" id="1">
                        <port/>
                        <speed units="Mbit">1</speed>
                    </interface>
                </network>
            </hardware>
        </machine>
        <host id="0">
            <name/>
            <domain/>
            <machine id="0"/>
            <description/>
            <os type="Linux"/>
            <addresses>
                <address id="1" hostname="hostname" type="IPv4" interface="1">1.2.3.4</address>
            </addresses>
            <axxon enabled="false">
                <shell>STAF</shell>
                <username>jbench</username>
                <capabilities/>
            </axxon>
            <jobgenerator enabled="false">
                <capabilities/>
                <restrictions/>
            </jobgenerator>
            <STAF trust="true">
                <entries/>
                <vars/>
            </STAF>
        </host>
    </template>
    <machines>
        <machine id="171">
            <name>Kermit</name>
            <serial/>
            <manufacturer>Intel</manufacturer>
            <model>Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz</model>
            <description>Broadwell</description>
            <location>
                <room>Heavy Lab</room>
                <site>Toronto</site>
                <country>Canada</country>
            </location>
            <owners>
                <owner id="1" type="eAMT">piyush286</owner>
            </owners>
            <architecture>
                <cpuvendor>Intel</cpuvendor>
                <cpuname>E5-2697 v4</cpuname>
                <cputype>AMD64</cputype>
                <bits>64</bits>
                <compatible id="1">
                    <cputype>x86</cputype>
                    <bits>32</bits>
                </compatible>
            </architecture>
            <hardware>
                <cpus>
                    <physical>36</physical>
                    <logical>72</logical>
                    <threading>SMT</threading>
                    <speed units="GHz">2.3</speed>
                </cpus>
                <fsbspeed units="MHz">1200</fsbspeed>
                <caches>
                    <cache id="1" type="L1d" units="KB">32</cache>
                    <cache id="2" type="L1i" units="KB">32</cache>
                    <notes/>
                </caches>
                <memory type="DDR">
                    <speed units="MHz">1200</speed>
                    <capacity units="GB">528</capacity>
                </memory>
                <network>
                    <interface id="1" type="Ethernet">
                        <port>BFS</port>
                        <speed units="Mbit">100</speed>
                    </interface>
                    <interface id="2" type="Ethernet">
                        <port>10G</port>
                        <speed units="Gbit">10</speed>
                    </interface>
                </network>
            </hardware>
        </machine>
    </machines>
    <hosts>
        <host id="242">
            <name>kermit</name>
            <domain>customServer.com</domain>
            <machine id="171"/>
            <description/>
            <os type="Linux">Ubuntu 16.04</os>
            <addresses>
                <address id="1" hostname="kermit" type="IPv4" interface="1">9.26.52.72</address>
                <address id="2" hostname="kermit10G" type="IPv4" interface="2">192.168.1.83</address>
            </addresses>
            <axxon enabled="true">
                <shell>STAF</shell>
                <username>jbench</username>
                <capabilities/>
            </axxon>
            <jobgenerator enabled="true">
                <capabilities>
                    <capability id="1" name="perffarm" bits="all">
                        <property id="1" name="JDKDirectory">/java/perffarm/sdks</property>
                        <property id="2" name="resultsDir">/usr/local/wasperfauto/results</property>
                        <property id="3" name="resultsID"/>
                        <property id="4" name="wasperfauto_version">{WPA/inst1/root}</property>
                        <property id="5" name="dumpDir">/dump</property>
                    </capability>
                    <capability id="7" name="StartupDT" bits="all">
                        <property id="1" name="appSrvProfile">StartupDT</property>
                        <property id="2" name="appSrvInstanceName">DayTrader30</property>
                        <property id="3" name="appSrvUserName">wasadmin</property>
                        <property id="4" name="appSrvPassword">wasadmin</property>
                    </capability>
                    <capability id="10" name="SOABench" bits="all">
                        <property id="1" name="clientMachines">perfxposh10G</property>
                        <property id="2" name="appSrvProfile">SOABench</property>
                        <property id="3" name="appSrvInstanceName">SOABench</property>
                    </capability>
                    <capability id="17" name="4way" bits="all">
                        <property id="1" name="CPUAffinity"> numactl --physcpubind=0,1,36,37 --membind=0</property>
                        <property id="2" name="CPUAffinityLiberty">numactl --physcpubind=0-3 --membind=0</property>
                        <property id="3" name="CPUAffinityILOG_WODM">numactl --physcpubind=0,1,36,37 --membind=0</property>
